### ISSUE TITLE
Update wfc3_env config (imminent astroconda deprecation; platform-specific build info)

### ISSUE THREAD

**Issue by astromariarosa** [spacetelescope/WFC3Library#20]
Not urgent, but we should look at updating the environment configuration so that we are no longer using `astroconda`. Will this look like setting up `stenv` and adding extra packages as needed? Or will `stenv` be too overpowered for what we require?

Also, we should update `wfc3_env` to remove build specifications (export `conda` environment with `--no-builds`) to avert platform-specific conflicts.

**Comment by FDauphin** [comment]
@astromariarosa Thanks for the suggestion; it has been updated accordingly in #33 and #65
