### ISSUE TITLE
Update README.md file to include notebook categories 

### ISSUE THREAD

**Issue by mackjenn** [spacetelescope/WFC3Library#52]
Let's try to update this once Annie's notebooks are finished and before the STAN goes out in ~2 weeks.  Suggested organization:

General Tools:
•	WFC3 Image Displayer and Analyzer
•	Exception Report Checklist - WFC3
•	Manual Recalibration with calwf3
•	Processing WFC3/UVIS Data with calwf3 Using the v1.0 CTE-Correction

IR Notebooks:
•	IMA Viewer
•	Masking Persistence in WFC3/IR Images 
•	How to use wfc3_dash on DASH data

IR Variable Background :
•	IR IMA Visualization Tools with An Example of Time Variable Background
•	Manual Recalibration with calwf3:  Turning off the IR Linear Ramp Fit
•	Correcting for Helium Line Emission Background in WFC3/IR Exposures using the "Flatten-Ramp" Technique
•	Correcting for Scattered Light in IR Exposures: Manually Subtracting Bad Reads
•	Correcting for Scattered Light in IR Exposures: Using calwf3 to Mask Bad Reads

Photometry : 
•	WFC3/UVIS Filter Transformations with stsynphot 
•	Flux Unit Conversions with synphot and stsynphot 
•	Synthetic Photometry Examples for WFC3 WFC3/UVIS Time-dependent Photometry 
•	Calculating WFC3 Zeropoints with STSynphot 
•	WFC3/UVIS Pixel Area Map Corrections for Subarrays

**Comment by FDauphin** [comment]
@mackjenn Thanks for the suggestion! Updated the README via #64.
